Feature: Loggeduser
@sce1
Scenario: Sign up
When I visit home page
Then I follow "Sign up"
Then I should see "Choose Chefname"
Then I should see "Email"
Then I should see "Password"
Then I fill in "chef_chefname" with "newchef1"
Then I fill in "chef_email" with "chef-new@example.com"
Then I fill in "chef_password" with "testpassword"
Then I fill in "chef_password_confirmation" with "testpassword"
Then I press "Create my account"
Then I should see "Welcome newchef1 to MyRecipes App!"
Then I should see "Recipes"
Then I follow "Recipes"
Then I follow "Create a new recipe"
Then I should see "Name"
Then I should see "Description"
Then I fill in "recipe_name" with "Sandwich"
Then I fill in "recipe_description" with "Toast the bread and add veggies"
Then I check "recipe_ingredient_ids_0"
Then I check "recipe_ingredient_ids_2"
Then I press "Create Recipe"
Then I should see "Edit this recipe"
Then I should see "Delete this recipe"
When I follow "Edit this recipe"
Then I fill in "recipe_name" with "Veg sandwich"
Then I press "Update Recipe"
Then I should see "Recipe was updated successfully!"
Then I should see "No Comments Yet!"
Then I fill in "comment_description" with "commenting out for testing"
Then I press "Submit Comment"
Then I should see "Comment was created successfully"
Then I follow "ingredient_ 2"
Then I should see "Recipe's containing ingredient_ 2"
Then I follow "Veg sandwich"
Then I should see "Steps:"
Then I should see "Created by:"
Then I clickicon "glyphicon-thumbs-up"
Then I should see "Your selection was succesful"
Then I clickicon "glyphicon-thumbs-up"
Then I should see "You can only like/dislike a recipe once"
Then I follow "Return to recipes listing"
Then I should see "All Recipes"
Then I follow "All Recipes" 
Then I follow "recipe_ 1"
Then I should see "Created by:"
Then I should see "Prior Comments"
Then I should not see "Edit this recipe"
Then I should not see "Delete this recipe"
Then I should see "Return to recipes listing"
Then I follow "Return to recipes listing"
Then I follow "ingredient_ 1"
Then I should see "Recipe's containing ingredient_ 1"
Then I follow "Ingredients"
Then I follow "Ingredient_ 3"
Then I should see "Recipe's containing ingredient_ 3"
Then I follow "recipe_ 3"
Then I should see "Steps:"
Then I should see "Created by:"
Then I clickicon "glyphicon-thumbs-up"
Then I should see "Your selection was succesful"
Then I clickicon "glyphicon-thumbs-down"
Then I should see "You can only like/dislike a recipe once"
Then I fill in "comment_description" with "commenting out for testing"
Then I press "Submit Comment"
Then I should see "Comment was created successfully"


