Feature: Nonloggeduser
@s1
Scenario: Nonlogged in user
When I visit home page
Then I should see "Log in"
When I follow "Chefs"
Then I should see "Showing all chefs"
When I follow "Chef 0"
Then I should see "Chef chef 0's profile"
Then I follow "recipe_ 0"
Then I should see "Steps:"
Then I should see "Created by:"
Then I clickicon "glyphicon-thumbs-down"
Then I should see "You must be logged in to perform that action"
Then I should see "Prior Comments"
Then I should not see "Edit this recipe"
Then I should not see "Delete this recipe"
Then I should see "Return to recipes listing"
Then I follow "Return to recipes listing"
Then I should see "All Recipes"
Then I follow "All Recipes" 
Then I follow "recipe_ 1"
Then I should see "Created by:"
Then I should see "Prior Comments"
Then I should not see "Edit this recipe"
Then I should not see "Delete this recipe"
Then I should see "Return to recipes listing"
Then I follow "Return to recipes listing"
Then I follow "ingredient_ 1"
Then I should see "Recipe's containing ingredient_ 1"
Then I follow "Ingredients"
Then I follow "Ingredient_ 2"
Then I should see "Recipe's containing ingredient_ 2"
Then I follow "recipe_ 2"
Then I should see "Steps:"
Then I should see "Created by:"
Then I clickicon "glyphicon-thumbs-up"
Then I should see "You must be logged in to perform that action"
Then I should see "Prior Comments"
Then I should not see "Edit this recipe"
Then I should not see "Delete this recipe"
Then I should see "Return to recipes listing"
Then I follow "Return to recipes listing"

@s2
Scenario: NonloggedUserActions

When I visit home page
Then I follow "View all recipes as a Guest!"
Then I should see "All recipes"
Then I follow "The Food Corner"
Then I should see "Sign up"
Then I follow "View Chefs listing"
Then I should see "Showing all chefs"
Then I follow "The Food Corner"
Then I should see "Sign up"
Then I follow "View ingredients listing"
Then I should see "Available ingredients"
Then I follow "The Food Corner"
Then I should see "Sign up"